## Get Review Rating for customer Sentiment

In [1]:
# import libraries 
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from sqlalchemy import create_engine
import urllib
import pyodbc

In [2]:
# download vader for dictionary 
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Salah_Eldin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [3]:
# fetch data from sql 
conn_str = (
    "Driver={ODBC Driver 18 for SQL Server};"
    "Server=SALAH\\SQLEXPRESS;"
    "Database=PortfolioProject_MarketingAnalytics;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

params = urllib.parse.quote_plus(conn_str)

engine = create_engine("mssql+pyodbc:///?odbc_connect=" + params)

query = "SELECT ReviewID, CustomerID, ProductID, ReviewDate, Rating, ReviewText FROM fact_customer_reviews"

customer_review_df = pd.read_sql(query, engine)

In [21]:
customer_review_df.head()

,ReviewID,CustomerID,ProductID,ReviewDate,Rating,ReviewText,SentimentScore,SentimentCategory,SentimentBucket
0,1,77,18,2023-12-23,3,"Average experience, nothing special.",-0.3089,Mixed Negative,-0.49 to 0.0
1,2,80,19,2024-12-25,5,The quality is top-notch.,0.0000,Positive,0.0 to 0.49
2,3,50,13,2025-01-26,4,Five stars for the quick delivery.,0.0000,Positive,0.0 to 0.49
3,4,78,15,2025-04-21,3,"Good quality, but could be cheaper.",0.2382,Mixed Positive,0.0 to 0.49
4,5,64,2,2023-07-16,3,"Average experience, nothing special.",-0.3089,Mixed Negative,-0.49 to 0.0

In [5]:
customer_review_df.describe()

         ReviewID   CustomerID    ProductID       Rating
count  1363.00000  1363.000000  1363.000000  1363.000000
mean    682.00000    51.701394    10.337491     3.686720
std     393.60852    28.605493     5.702922     1.180243
min       1.00000     1.000000     1.000000     1.000000
25%     341.50000    27.000000     5.000000     3.000000
50%     682.00000    53.000000    10.000000     4.000000
75%    1022.50000    77.000000    15.000000     5.000000
max    1363.00000   100.000000    20.000000     5.000000

In [6]:
customer_review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1363 entries, 0 to 1362
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ReviewID    1363 non-null   int64
 1   CustomerID  1363 non-null   int64
 2   ProductID   1363 non-null   int64
 3   ReviewDate  1363 non-null   object
 4   Rating      1363 non-null   int64
 5   ReviewText  1363 non-null   object
dtypes: int64(4), object(2)
memory usage: 64.0+ KB

In [7]:
customer_review_df.isnull().sum()

ReviewID      0
CustomerID    0
ProductID     0
ReviewDate    0
Rating        0
ReviewText    0
dtype: int64

In [8]:
# create Senitment analyzer with VADER
sia = SentimentIntensityAnalyzer()

In [9]:
sia.lexicon.update({
    "top-notch": 3.0,
    "quick delivery": 2.5,
    "high quality": 2.0,
    "bad": -2.5,
    "worst": -3.0
})

In [10]:
def calculate_sentiment(review):
    sentiment = sia.polarity_scores(review)
    return sentiment['compound']

In [11]:
def categorize_sentiment(score, rating):
     # Use both the text sentiment score and the numerical rating to determine sentiment category
    if score > 0.05:  # Positive sentiment score
        if rating >= 4:
            return 'Positive'  # High rating and positive sentiment
        elif rating == 3:
            return 'Mixed Positive'  # Neutral rating but positive sentiment
        else:
            return 'Mixed Negative'  # Low rating but positive sentiment
    elif score < -0.05:  # Negative sentiment score
        if rating <= 2:
            return 'Negative'  # Low rating and negative sentiment
        elif rating == 3:
            return 'Mixed Negative'  # Neutral rating but negative sentiment
        else:
            return 'Mixed Positive'  # High rating but negative sentiment
    else:  # Neutral sentiment score
        if rating >= 4:
            return 'Positive'  # High rating with neutral sentiment
        elif rating <= 2:
            return 'Negative'  # Low rating with neutral sentiment
        else:
            return 'Neutral'

In [12]:
def sentiment_bucket(score):
    if score >= 0.5:
        return '0.5 to 1.0'  # Strongly positive sentiment
    elif 0.0 <= score < 0.5:
        return '0.0 to 0.49'  # Mildly positive sentiment
    elif -0.5 <= score < 0.0:
        return '-0.49 to 0.0'  # Mildly negative sentiment
    else:
        return '-1.0 to -0.5'

In [13]:
# apply calculation in SentimentScore 
customer_review_df['SentimentScore'] = customer_review_df['ReviewText'].apply(calculate_sentiment)

In [14]:
customer_review_df['SentimentCategory'] = customer_review_df.apply(
    lambda row: categorize_sentiment(row['SentimentScore'], row['Rating']), axis=1)

In [15]:
customer_review_df['SentimentBucket'] = customer_review_df['SentimentScore'].apply(sentiment_bucket)

In [19]:
customer_review_df.head()

,ReviewID,CustomerID,ProductID,ReviewDate,Rating,ReviewText,SentimentScore,SentimentCategory,SentimentBucket
0,1,77,18,2023-12-23,3,"Average experience, nothing special.",-0.3089,Mixed Negative,-0.49 to 0.0
1,2,80,19,2024-12-25,5,The quality is top-notch.,0.0000,Positive,0.0 to 0.49
2,3,50,13,2025-01-26,4,Five stars for the quick delivery.,0.0000,Positive,0.0 to 0.49
3,4,78,15,2025-04-21,3,"Good quality, but could be cheaper.",0.2382,Mixed Positive,0.0 to 0.49
4,5,64,2,2023-07-16,3,"Average experience, nothing special.",-0.3089,Mixed Negative,-0.49 to 0.0

In [20]:
customer_review_df.to_csv('fact_customer_reviews_with_sentiment.csv', index=False)